appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: xLmoQF47Mg3yboQ4bOZLooI0MxBxI6Mt4hTWXf2w6PDK5sIK3MjjPgwYGGSYfWd8/a3w55P8/V8JJ60nMDdpoWz+cABxgjjG1XAQ9a5PhCs3Cq+YX9Lf4aXta9dtv2jiYI85uYWm6EPWQItbL+8zX4ZKPtj6Tn1NCsZGgA5xIGekff+PZMPHjSSfp+hzKuXD0PmOjH7QWAr46tjmVfinB4hkrQZbjPBpj4qAQNzFXb/BWGN7DCiDFOa97pifAcpWjoBIqZliCL9uPJGl8SjtQnYGIYWrILuQn8PfCOh3Ugzw2pYVSEODDprKKVvln5Ok0ZXlwK+Ez45jQ4RkVAWpCkQIU0Fl6/s0OERdWO51SzxMuGMoR7P9OrPcyScE5TPuHYuIMUlIpwB2Ot7NhYusBXDK1ZcxZwMpzUYIyWqyZJAvOh+PE+TgcY7uU2lB0pu5LmFt2YvAMonKzoOoUrKp7ViPWiO8hBRue7r4n7rUwHLhgPoBbyNuxKU3C4Nb56GEManKwvwdSBi+Bflc3MNS3XA3fw3VHy3SHl4RMg+dsed/y5VNNqUyJv0ivV0WBH8rRQ/yfPmAXIGZ3XFcNef6L6NpcGzb5mIlyI2315pl5N+cTX+qDFVzYFktAH9cI53jlOvdfsA5c8LRk/d9u/kCqNPNNy1q6sXYijBIE0wCPcg=}
bot:
  automerge: true
